"""DGX Spark convergent install: Speaches Whisper server via Docker (#814).

Installs the Whisper transcription service that prod
(``cloud_with_dgx_primary.yaml``) targets via the tailnet. Speaches
is the renamed upstream of ``faster-whisper-server`` — same OpenAI-compatible
API surface, distributed as a CUDA Docker image (the pip package was abandoned
at v0.0.2).

What this lays down on DGX:

- A ``docker-compose.yml`` at ``/opt/faster-whisper/docker-compose.yml`` that
  pulls ``ghcr.io/speaches-ai/speaches:latest-cuda`` and exposes :8000.
- The container is configured with ``restart: unless-stopped`` so it survives
  reboots without a systemd wrapper. Docker daemon already starts at boot.
- A model preload is NOT done in this recipe — Speaches downloads on first
  request (~3 GB for ``Systran/faster-whisper-large-v3``). First transcribe is
  slow; subsequent are fast.

What this deliberately does NOT do:

- Install Docker. The DGX has it from #810 bring-up (operator runs vLLM
  experiments via Docker).
- Wire systemd. Compose's ``restart: unless-stopped`` is enough; one fewer
  moving part. Crash-restart hardening (OOM detection, restart-rate-limit)
  stays out of scope — see #910.

Idempotent: re-running ``make dgx-deploy`` re-renders the compose YAML +
``docker compose up -d``. Container is recreated only when image / config
changes; otherwise no-op.

Operator manual steps still pending (per #810):

- NVIDIA driver + CUDA runtime install.
- HuggingFace cache pre-warm if you want to avoid the ~3 GB first-request
  download latency.

Verify with ``make dgx-verify``.
"""

from __future__ import annotations

from pyinfra.operations import files, server

# Knobs the downstream code (the provider client) expects:
#
# - PORT 8000 — added to the dgx-llm-host ACL alongside :11434 in
#   tailscale/policy.hujson. Don't change without updating the ACL.
# - MODEL ID — Hugging Face repo ID. ``Systran/faster-whisper-large-v3`` is
#   the upstream-recommended unquantized large-v3 weights; Speaches fetches
#   on first request.
SERVICE_NAME = "faster-whisper"
INSTALL_ROOT = "/opt/faster-whisper"
COMPOSE_FILE = f"{INSTALL_ROOT}/docker-compose.yml"
IMAGE = "ghcr.io/speaches-ai/speaches:latest-cuda"
PORT = 8000
MODEL = "Systran/faster-whisper-large-v3"

# HF config lives in the operator's ``~/.env`` on DGX (single source of truth
# for HF_TOKEN / HF_HOME / HF_HUB_CACHE / HF_DATASETS_CACHE). Compose injects it
# via ``env_file:``. The model cache itself is shared with vLLM (also bind-mounts
# /opt/llm-models/huggingface) so weights aren't duplicated.
OPERATOR_ENV_FILE = "/home/markodragoljevic/.env"
HF_CACHE_HOST = "/opt/llm-models/huggingface"

# 1. Install root only — no separate HF cache directory needed; the operator's
# centralized cache at /opt/llm-models/huggingface is the bind-mount target.
files.directory(
    name="dir: /opt/faster-whisper (install root)",
    path=INSTALL_ROOT,
    mode="755",
    present=True,
    _sudo=True,
)

# 2. docker-compose.yml.
#
# `network_mode: host` so the container binds :8000 directly on the host
# (matching Ollama's :11434 pattern, which is how the tailnet ACL boundary
# becomes the real network gate). Without this we'd need explicit -p 8000:8000
# and the tailscale ACL would still only see the host-side socket — host mode
# is cleaner.
COMPOSE_CONTENT = f"""# Auto-generated by infra/dgx/converge/deploy.py. Edit there, not here.
# Re-run ``make dgx-deploy`` from the laptop to redeploy.

services:
  {SERVICE_NAME}:
    image: {IMAGE}
    container_name: {SERVICE_NAME}
    restart: unless-stopped
    network_mode: host
    runtime: nvidia
    # HF_TOKEN / HF_HOME / HF_HUB_CACHE / HF_DATASETS_CACHE all come from the
    # operator's centralized ~/.env on DGX. Update there to update everywhere.
    env_file:
      - {OPERATOR_ENV_FILE}
    environment:
      # Compose-specific (NOT in ~/.env): Speaches-only knobs.
      - WHISPER__MODEL={MODEL}
      - WHISPER__DEVICE=cuda
      # default (-> float32) is the only compute type that runs efficiently on
      # this GB10 build. See #948 for the full investigation. Findings (2026-06-09):
      #   - ``float16`` / ``bfloat16`` HARD-ERROR ("target device or backend do not
      #     support efficient <type> computation") — the shipped CTranslate2 build
      #     has no Blackwell (sm_100/sm_120) fp16/bf16 kernels.
      #   - ``int8`` loads but CRAWLS on real episodes (19-min episode ran 5+ min vs
      #     fp32's ~68s/34min) — likely no int8 GPU kernel either, silent slow path.
      #   - ``default`` infers fp16 from the model, can't run it, and converts to
      #     ``float32`` (logged) — this is the path that actually works at speed.
      # NOTE: ``nvidia-smi`` util% is UNRELIABLE on GB10 (unified memory, reports 0%
      # mid-transcription) — judge compute by wall-time, not nvidia-smi. Revisit if a
      # Blackwell-kernel CTranslate2 build lands (then bf16 would be preferable). #948.
      - WHISPER__COMPUTE_TYPE=default
      - LOG_LEVEL=INFO
      - ENABLE_UI=false
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT={PORT}
    volumes:
      # Mount HF cache at the SAME path inside the container as outside, so
      # HF_HOME=/opt/llm-models/huggingface (from ~/.env) resolves correctly
      # from inside. Shared with vLLM's compose so weights aren't duplicated.
      - {HF_CACHE_HOST}:{HF_CACHE_HOST}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
"""

server.shell(
    name="compose: write /opt/faster-whisper/docker-compose.yml",
    commands=[
        f"cat > {COMPOSE_FILE} <<'EOF'\n{COMPOSE_CONTENT}EOF",
        f"chmod 644 {COMPOSE_FILE}",
    ],
    _sudo=True,
)

# 3. Pull image + start. Idempotent: docker compose only recreates the
# container if the YAML config-hash or image digest changed.
#
# The pull is wrapped in `|| true` so a GHCR slowdown/outage doesn't bail
# the whole deploy. We observed this on 2026-06-08: ghcr.io took >30s to
# respond, pyinfra dropped to "Error: executed 0 commands" + "No hosts
# remaining", and the pyannote install steps further down never ran. With
# the pull tolerated, `docker compose up -d` below uses the locally-cached
# image — fine for the common case where Speaches is already running on
# DGX and we're only redeploying pyannote. The trade-off: a deploy could
# silently miss a NEW upstream image. We accept that since (a) the timing
# message still surfaces success vs warn-only-fall-through, (b) the next
# successful deploy still picks up changes, and (c) image bumps are rare
# enough that catching them via an explicit `dgx-refresh` target later is
# a better tool for the job than gating every deploy on GHCR reachability.
server.shell(
    name="compose: pull image (tolerated; falls back to cached on GHCR blip)",
    commands=[
        f"cd {INSTALL_ROOT} && docker compose pull "
        f"|| echo '::warning::GHCR pull failed; will use cached image if present'"
    ],
    _sudo=True,
)

server.shell(
    name="compose: up -d (start / restart on config change)",
    commands=[f"cd {INSTALL_ROOT} && docker compose up -d"],
    _sudo=True,
)


# ---------------------------------------------------------------------------
# #926 — pyannote diarization service. Same shape as Speaches install above:
# Docker-managed, restart: unless-stopped, env_file shared with the operator's
# centralized ~/.env (HF_TOKEN comes from there). Listens on :8001 — the
# legacy embedding-shim slot, already in the tailnet ACL.
# ---------------------------------------------------------------------------

PYANNOTE_INSTALL_ROOT = "/opt/pyannote-server"
PYANNOTE_COMPOSE_FILE = f"{PYANNOTE_INSTALL_ROOT}/docker-compose.yml"
PYANNOTE_BUILD_CTX = f"{PYANNOTE_INSTALL_ROOT}/build"
PYANNOTE_IMAGE = "podcast-pyannote:0.1.0"
PYANNOTE_PORT = 8001
PYANNOTE_MODEL = "pyannote/speaker-diarization-3.1"
# We BUILD the image on DGX (no public registry yet) — sources for the
# Dockerfile + app live in the repo at infra/dgx/pyannote-server/. The
# deploy reads those files and ships their contents up.
from pathlib import Path as _Path

_PYANNOTE_SRC = _Path(__file__).resolve().parents[1] / "pyannote-server"

# Install root for the service compose + build context.
files.directory(
    name="dir: /opt/pyannote-server (install root)",
    path=PYANNOTE_INSTALL_ROOT,
    mode="755",
    present=True,
    _sudo=True,
)

files.directory(
    name="dir: /opt/pyannote-server/build (Docker build context)",
    path=PYANNOTE_BUILD_CTX,
    mode="755",
    present=True,
    _sudo=True,
)

# Push Dockerfile + app.py to the build context on DGX.
files.put(
    name="ship: pyannote-server/Dockerfile",
    src=str(_PYANNOTE_SRC / "Dockerfile"),
    dest=f"{PYANNOTE_BUILD_CTX}/Dockerfile",
    mode="644",
    create_remote_dir=False,
    _sudo=True,
)

files.put(
    name="ship: pyannote-server/app.py",
    src=str(_PYANNOTE_SRC / "app.py"),
    dest=f"{PYANNOTE_BUILD_CTX}/app.py",
    mode="644",
    create_remote_dir=False,
    _sudo=True,
)

# docker-compose.yml. Same env_file pattern as Speaches → HF_TOKEN flows
# from the operator's centralized ~/.env. HF cache shared with Speaches +
# vLLM at /opt/llm-models/huggingface so we don't re-download the model.
PYANNOTE_COMPOSE_CONTENT = f"""# Auto-generated. Edit infra/dgx/converge/deploy.py instead.
# Re-run ``make dgx-deploy`` from the laptop to redeploy.

services:
  pyannote:
    build: {PYANNOTE_BUILD_CTX}
    image: {PYANNOTE_IMAGE}
    container_name: pyannote
    restart: unless-stopped
    network_mode: host
    runtime: nvidia
    env_file:
      - {OPERATOR_ENV_FILE}
    environment:
      - PYANNOTE_MODEL={PYANNOTE_MODEL}
      - PYANNOTE_DEVICE=cuda
      - LOG_LEVEL=INFO
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT={PYANNOTE_PORT}
    volumes:
      - {HF_CACHE_HOST}:{HF_CACHE_HOST}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
"""

server.shell(
    name="compose: write /opt/pyannote-server/docker-compose.yml",
    commands=[
        f"cat > {PYANNOTE_COMPOSE_FILE} <<'EOF'\n{PYANNOTE_COMPOSE_CONTENT}EOF",
        f"chmod 644 {PYANNOTE_COMPOSE_FILE}",
    ],
    _sudo=True,
)

server.shell(
    name="build: pyannote image (one-time + on Dockerfile/app changes)",
    commands=[f"cd {PYANNOTE_INSTALL_ROOT} && docker compose build"],
    _sudo=True,
)

server.shell(
    name="compose: up -d (start / restart pyannote service)",
    commands=[f"cd {PYANNOTE_INSTALL_ROOT} && docker compose up -d"],
    _sudo=True,
)


# ---------------------------------------------------------------------------
# #953 — openai-whisper transcription service. Runs alongside the speaches
# faster-whisper container on a different port (8002). Reason: speaches'
# bundled ctranslate2 is a community reimplementation of Whisper inference
# (#948 surfaced this). Until #952 validates that faster-whisper's WER
# matches openai-whisper on real podcasts, we want a first-party path
# available. Both services run side-by-side; the consumer picks via URL.
# Same Docker-based shape as Speaches + pyannote.
# ---------------------------------------------------------------------------

WHISPER_INSTALL_ROOT = "/opt/whisper-server"
WHISPER_COMPOSE_FILE = f"{WHISPER_INSTALL_ROOT}/docker-compose.yml"
WHISPER_BUILD_CTX = f"{WHISPER_INSTALL_ROOT}/build"
WHISPER_IMAGE = "podcast-whisper:0.1.0"
WHISPER_PORT = 8002
WHISPER_MODEL = "large-v3"
# Persistent cache for openai-whisper model weights (~3GB for large-v3).
# Separate from the HF cache because openai-whisper uses its own cache layout
# (URL-hashed filenames, not HF's snapshots/blobs structure).
WHISPER_CACHE_HOST = "/opt/llm-models/whisper-cache"

_WHISPER_SRC = _Path(__file__).resolve().parents[1] / "whisper-server"

files.directory(
    name="dir: /opt/whisper-server (install root)",
    path=WHISPER_INSTALL_ROOT,
    mode="755",
    present=True,
    _sudo=True,
)

files.directory(
    name="dir: /opt/whisper-server/build (Docker build context)",
    path=WHISPER_BUILD_CTX,
    mode="755",
    present=True,
    _sudo=True,
)

files.directory(
    name="dir: /opt/llm-models/whisper-cache (model weights persistence)",
    path=WHISPER_CACHE_HOST,
    mode="755",
    present=True,
    _sudo=True,
)

files.put(
    name="ship: whisper-server/Dockerfile",
    src=str(_WHISPER_SRC / "Dockerfile"),
    dest=f"{WHISPER_BUILD_CTX}/Dockerfile",
    mode="644",
    create_remote_dir=False,
    _sudo=True,
)

files.put(
    name="ship: whisper-server/app.py",
    src=str(_WHISPER_SRC / "app.py"),
    dest=f"{WHISPER_BUILD_CTX}/app.py",
    mode="644",
    create_remote_dir=False,
    _sudo=True,
)

# docker-compose.yml. Same env_file + GPU passthrough as the other two
# services. Whisper cache is OUTSIDE the operator's HF cache because
# openai-whisper writes its own URL-hashed layout, not HF's snapshots.
WHISPER_COMPOSE_CONTENT = f"""# Auto-generated. Edit infra/dgx/converge/deploy.py instead.
# Re-run ``make dgx-deploy`` from the laptop to redeploy.

services:
  whisper-openai:
    build: {WHISPER_BUILD_CTX}
    image: {WHISPER_IMAGE}
    container_name: whisper-openai
    restart: unless-stopped
    network_mode: host
    runtime: nvidia
    env_file:
      - {OPERATOR_ENV_FILE}
    environment:
      - WHISPER_MODEL={WHISPER_MODEL}
      - WHISPER_DEVICE=cuda
      - WHISPER_CACHE_DIR=/root/.cache/whisper
      - LOG_LEVEL=INFO
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT={WHISPER_PORT}
    volumes:
      # Persistent model cache so the ~3GB large-v3 download survives
      # container restarts. openai-whisper writes to /root/.cache/whisper.
      - {WHISPER_CACHE_HOST}:/root/.cache/whisper
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
"""

server.shell(
    name="compose: write /opt/whisper-server/docker-compose.yml",
    commands=[
        f"cat > {WHISPER_COMPOSE_FILE} <<'EOF'\n{WHISPER_COMPOSE_CONTENT}EOF",
        f"chmod 644 {WHISPER_COMPOSE_FILE}",
    ],
    _sudo=True,
)

server.shell(
    name="build: whisper-openai image (one-time + on Dockerfile/app changes)",
    commands=[f"cd {WHISPER_INSTALL_ROOT} && docker compose build"],
    _sudo=True,
)

server.shell(
    name="compose: up -d (start / restart whisper-openai service)",
    commands=[f"cd {WHISPER_INSTALL_ROOT} && docker compose up -d"],
    _sudo=True,
)


# ---------------------------------------------------------------------------
# #928 — vllm-autoresearch. NVIDIA-prebuilt vLLM container serving an
# open-weight LLM for autoresearch evaluations (summary / GI / KG).
# Listens on :8003 so it coexists with the other DGX services (8000=
# speaches, 8001=pyannote, 8002=openai-whisper). No Dockerfile — vLLM
# ships its own OpenAI-compatible server in the NVIDIA image.
# ---------------------------------------------------------------------------

VLLM_INSTALL_ROOT = "/opt/vllm-autoresearch"
VLLM_COMPOSE_FILE = f"{VLLM_INSTALL_ROOT}/docker-compose.yml"
# NVIDIA tag history on this GB10 (per the #928 Cell C investigation):
# - 25.11-py3: vLLM 0.11 / transformers 4.57.1 — works; was the prior
#   default. Does NOT support qwen3_5_moe architecture (the Qwen3.5/3.6
#   model family). Use if you need to revert to R1-Distill or older
#   Qwen3 models.
# - 26.01-py3 through 26.04-py3: NVIDIA shipped them with transformers
#   4.57.x patches; still no qwen3_5_moe support. Don't bother.
# - 26.05-py3: vLLM 0.20.1 / transformers 5.6.0. Supports qwen3_5_moe
#   AND boots on GB10. Current default per Cell C.
# - 26.05.post1-py3: post-release hotfix that broke on this operator's
#   GB10 (verified by operator). Do NOT use even though it would also
#   support qwen3_5_moe.
VLLM_IMAGE = "nvcr.io/nvidia/vllm:26.05-py3"
VLLM_PORT = 8003

# Default to Qwen3.6-35B-A3B (same model family as the Ollama
# qwen3.5:35b champion from #928). Cell C verified vLLM-served Qwen3.6
# at bf16 ties Ollama-served qwen3.5:35b at Q4_K_M within scoring
# noise (Sonnet 4.6: 4.90 vs 5.00). The R1-Distill alternative is in
# /opt/llm-models/huggingface/ if you need to revert — set this back
# to ``deepseek-ai/DeepSeek-R1-Distill-Qwen-32B`` and switch
# VLLM_IMAGE to 25.11-py3. See infra/dgx/vllm-autoresearch/README.md.
VLLM_MODEL = "Qwen/Qwen3.6-35B-A3B"
# 0.60 (not 0.92) so vLLM coexists with the other DGX services:
# whisper-openai (~3 GB) + pyannote (~3-4 GB) + faster-whisper (~3-4 GB)
# + Ollama-loaded model (~10 GB depending on what's resident) →
# ~15-20 GB already in use of the GB10's ~122 GB. 0.60 = ~73 GB,
# which fits a 35B bf16 model + KV cache while leaving headroom for
# the other services. Bump back toward 0.92 only if you stop the
# other services to give vLLM the whole box.
VLLM_GPU_MEM_UTIL = "0.60"
# 32k context — enough for podcast transcripts (~10k chars typical,
# ~13k tokens at the model's tokenizer rate). Qwen3.6-35B-A3B
# supports 32768 natively at this max-num-seqs; bigger contexts need
# either lowering max-num-seqs further or raising GPU_MEM_UTIL.
VLLM_MAX_MODEL_LEN = "32768"
# Qwen3.6-35B-A3B uses Mamba layers; vLLM 0.20 enforces
# max_num_seqs ≤ Mamba cache blocks. Default 256 fails CUDA-graph
# capture (only 190 cache blocks available at gpu_mem_util=0.60).
# 128 is well below the limit with headroom. Tune up only if you
# raise gpu_mem_util or change the model family. Not used by the
# 25.11-py3 / R1-Distill alternative — safe to leave in place.
VLLM_MAX_NUM_SEQS = "128"

files.directory(
    name="dir: /opt/vllm-autoresearch (install root)",
    path=VLLM_INSTALL_ROOT,
    mode="755",
    present=True,
    _sudo=True,
)

# docker-compose.yml. Mirrors the operator's working
# ``~/docker-compose/vllm-Qwen3-Coder-Next/docker-compose.yml`` byte-for-byte
# except for the port (8003 not 8000) and container name (so it coexists
# with the operator's personal coding container if/when that runs).
VLLM_COMPOSE_CONTENT = f"""# Auto-generated. Edit infra/dgx/converge/deploy.py instead.
# Re-run ``make dgx-deploy`` from the laptop to redeploy.

services:
  vllm-autoresearch:
    image: {VLLM_IMAGE}
    container_name: vllm-autoresearch
    runtime: nvidia
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    network_mode: host
    env_file:
      - {OPERATOR_ENV_FILE}
    volumes:
      - {HF_CACHE_HOST}:/root/.cache/huggingface
    environment:
      - HF_HOME=/root/.cache/huggingface
      - HF_HUB_CACHE=/root/.cache/huggingface
      # GB10 hotfix: torch.compile has been the Blackwell sore spot on
      # the version we run. Disabling loses ~10-20% steady-state throughput
      # but is the reliable boot path per the operator's working composes.
      - VLLM_DISABLE_TORCH_COMPILE=1
      - NVIDIA_VISIBLE_DEVICES=all
    command:
      - vllm
      - serve
      - {VLLM_MODEL}
      - --host
      - 0.0.0.0
      - --port
      - "{VLLM_PORT}"
      - --dtype
      - bfloat16
      - --max-model-len
      - "{VLLM_MAX_MODEL_LEN}"
      - --gpu-memory-utilization
      - "{VLLM_GPU_MEM_UTIL}"
      - --max-num-seqs
      - "{VLLM_MAX_NUM_SEQS}"
    healthcheck:
      test: ["CMD", "python3", "-c",
             "import urllib.request; urllib.request.urlopen('http://localhost:{VLLM_PORT}/health')"]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 600s
    restart: unless-stopped
"""

server.shell(
    name="compose: write /opt/vllm-autoresearch/docker-compose.yml",
    commands=[
        f"cat > {VLLM_COMPOSE_FILE} <<'EOF'\n{VLLM_COMPOSE_CONTENT}EOF",
        f"chmod 644 {VLLM_COMPOSE_FILE}",
    ],
    _sudo=True,
)

# No build step — we use the NVIDIA-prebuilt image directly.
# We DO pull because the image is fairly recent (25.11) and the operator
# may not have it cached on initial deploy. Wrap in `|| true` so a
# pull blip doesn't bail the deploy when a cached image exists.
server.shell(
    name="compose: pull vllm image (tolerated on cache hit)",
    commands=[
        f"cd {VLLM_INSTALL_ROOT} && docker compose pull "
        f"|| echo '::warning::nvcr.io pull failed; falling back to cached image'"
    ],
    _sudo=True,
)

server.shell(
    name="compose: up -d (start / restart vllm-autoresearch service)",
    commands=[f"cd {VLLM_INSTALL_ROOT} && docker compose up -d"],
    _sudo=True,
)
