"""DGX Spark convergent install: Speaches Whisper server via Docker (#814).

Installs the Whisper transcription service that prod
(``cloud_with_dgx_whisper_primary.yaml``) targets via the tailnet. Speaches
is the renamed upstream of ``faster-whisper-server`` — same OpenAI-compatible
API surface, distributed as a CUDA Docker image (the pip package was abandoned
at v0.0.2).

What this lays down on DGX:

- A ``docker-compose.yml`` at ``/opt/faster-whisper/docker-compose.yml`` that
  pulls ``ghcr.io/speaches-ai/speaches:latest-cuda`` and exposes :8000.
- The container is configured with ``restart: unless-stopped`` so it survives
  reboots without a systemd wrapper. Docker daemon already starts at boot.
- A model preload is NOT done in this recipe — Speaches downloads on first
  request (~3 GB for ``Systran/faster-whisper-large-v3``). First transcribe is
  slow; subsequent are fast.

What this deliberately does NOT do:

- Install Docker. The DGX has it from #810 bring-up (operator runs vLLM
  experiments via Docker).
- Wire systemd. Compose's ``restart: unless-stopped`` is enough; one fewer
  moving part. Crash-restart hardening (OOM detection, restart-rate-limit)
  stays out of scope — see #910.

Idempotent: re-running ``make dgx-deploy`` re-renders the compose YAML +
``docker compose up -d``. Container is recreated only when image / config
changes; otherwise no-op.

Operator manual steps still pending (per #810):

- NVIDIA driver + CUDA runtime install.
- HuggingFace cache pre-warm if you want to avoid the ~3 GB first-request
  download latency.

Verify with ``make dgx-verify``.
"""

from __future__ import annotations

from pyinfra.operations import files, server

# Knobs the downstream code (the provider client) expects:
#
# - PORT 8000 — added to the dgx-llm-host ACL alongside :11434 in
#   tailscale/policy.hujson. Don't change without updating the ACL.
# - MODEL ID — Hugging Face repo ID. ``Systran/faster-whisper-large-v3`` is
#   the upstream-recommended unquantized large-v3 weights; Speaches fetches
#   on first request.
SERVICE_NAME = "faster-whisper"
INSTALL_ROOT = "/opt/faster-whisper"
COMPOSE_FILE = f"{INSTALL_ROOT}/docker-compose.yml"
IMAGE = "ghcr.io/speaches-ai/speaches:latest-cuda"
PORT = 8000
MODEL = "Systran/faster-whisper-large-v3"
HF_CACHE_HOST = "/opt/faster-whisper/hf-cache"

# 1. Install root + HF cache dir (model weights persist between container restarts).
files.directory(
    name="dir: /opt/faster-whisper (install root)",
    path=INSTALL_ROOT,
    mode="755",
    present=True,
    _sudo=True,
)

files.directory(
    name="dir: /opt/faster-whisper/hf-cache (model weights persist here)",
    path=HF_CACHE_HOST,
    # 1000:1000 matches the ``ubuntu`` user inside the Speaches container.
    # Without this, the container can't write to the bind-mounted cache dir
    # and ``/v1/models`` 500s on first scan.
    user="1000",
    group="1000",
    mode="755",
    present=True,
    _sudo=True,
)

# 2. docker-compose.yml.
#
# `network_mode: host` so the container binds :8000 directly on the host
# (matching Ollama's :11434 pattern, which is how the tailnet ACL boundary
# becomes the real network gate). Without this we'd need explicit -p 8000:8000
# and the tailscale ACL would still only see the host-side socket — host mode
# is cleaner.
COMPOSE_CONTENT = f"""# Auto-generated by infra/dgx/converge/deploy.py. Edit there, not here.
# Re-run ``make dgx-deploy`` from the laptop to redeploy.

services:
  {SERVICE_NAME}:
    image: {IMAGE}
    container_name: {SERVICE_NAME}
    restart: unless-stopped
    network_mode: host
    runtime: nvidia
    environment:
      # Speaches env vars (see https://github.com/speaches-ai/speaches).
      - WHISPER__MODEL={MODEL}
      - WHISPER__DEVICE=cuda
      - WHISPER__COMPUTE_TYPE=float16
      - LOG_LEVEL=INFO
      - ENABLE_UI=false
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT={PORT}
      # Speaches runs as the ``ubuntu`` user (UID 1000) inside the container,
      # so HF cache lives under /home/ubuntu/.cache. The host bind-mount is
      # chown'd to 1000:1000 above so the container can write the model.
    volumes:
      - {HF_CACHE_HOST}:/home/ubuntu/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
"""

server.shell(
    name="compose: write /opt/faster-whisper/docker-compose.yml",
    commands=[
        f"cat > {COMPOSE_FILE} <<'EOF'\n{COMPOSE_CONTENT}EOF",
        f"chmod 644 {COMPOSE_FILE}",
    ],
    _sudo=True,
)

# 3. Pull image + start. Idempotent: docker compose only recreates the
# container if the YAML config-hash or image digest changed.
server.shell(
    name="compose: pull image (separate step so the timing surfaces)",
    commands=[f"cd {INSTALL_ROOT} && docker compose pull"],
    _sudo=True,
)

server.shell(
    name="compose: up -d (start / restart on config change)",
    commands=[f"cd {INSTALL_ROOT} && docker compose up -d"],
    _sudo=True,
)
