"""The ``new-episodes.v1`` golden fixture is GENERATED by the real builders, never written by hand.

Email delivery was down for 33 h (2026-10-02/03) because the homelab template read a field the app
never sends, and nothing caught it: the delivery contract had no ``new-episodes.v1`` fixture at
all, and the real envelope failed the schema four ways. A hand-written fixture would only move the
problem — it can drift from what the app sends exactly as the template did.

So the fixture is produced here, over a small synthetic corpus, through the same code path the
dispatcher runs: ``new_in_follows_items`` → ``assemble_new_episodes_payload`` →
``build_email_envelope``. The test fails when the committed golden differs from what the builder
emits; regenerate with ``UPDATE_GOLDEN=1``. ``test_delivery_envelope_contract.py`` then validates
the golden against the schema, and the homelab contract test renders it.

The push envelope is checked against the schema here directly rather than as a second golden: it
is what the push worker reads, and before this test existed it put the subscription where no
worker looks.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest
from jsonschema import Draft202012Validator

from podcast_scraper.server import app_new_episode_digest as ned, app_user_state
from podcast_scraper.server.app_slugs import episode_slug
from podcast_scraper.server.app_user_store import get_or_create_user

# `app` explicitly: the marker is auto-applied only to test_app_*.py, and without it the PR suite
# (`integration and (critical_path or app)`) never ran this golden — it ran only post-merge.
pytestmark = [pytest.mark.integration, pytest.mark.app]

_REPO = Path(__file__).resolve().parents[3]
_SCHEMA = _REPO / "docs" / "api" / "delivery-envelope.schema.json"
_GOLDEN = _REPO / "tests" / "fixtures" / "delivery" / "new-episodes.v1.golden.json"

#: Fixed so the golden is byte-stable: 2026-09-15T10:00:00Z, outside the default quiet hours.
_NOW = 1789466400

#: A consenting user's comms, as `app_comms_store` stores them. The ref is a fixed stand-in for
#: the random one the store mints; the contract only requires it to be non-empty.
_COMMS = {
    "types": {"new_episodes": {"email": True, "push": True}},
    "unsubscribe_ref": "unsub_golden_ref",
    "timezone": "UTC",
}


def _write_ep(
    root: Path, *, stem: str, feed_id: str, episode_id: str, topic: tuple[str, str]
) -> str:
    """One corpus episode (metadata + KG). Mirrors the your-week corpus e2e helper."""
    meta = root / "metadata"
    meta.mkdir(parents=True, exist_ok=True)
    (root / "transcripts").mkdir(parents=True, exist_ok=True)
    rel = f"metadata/{stem}.metadata.json"
    doc = {
        "feed": {"feed_id": feed_id, "title": f"Show {feed_id}", "url": "https://p/f.xml"},
        "episode": {
            "episode_id": episode_id,
            "title": f"Episode {episode_id}",
            "published_date": f"2026-09-1{stem[-1]}T00:00:00",
            "duration_seconds": 1000,
        },
        "summary": {"title": "S", "bullets": ["a"]},
        "content": {"transcript_file_path": f"transcripts/{stem}.txt"},
    }
    (meta / f"{stem}.metadata.json").write_text(json.dumps(doc), encoding="utf-8")
    (root / "transcripts" / f"{stem}.txt").write_text("hello world", encoding="utf-8")
    kg = {
        "episode_id": episode_id,
        "nodes": [{"id": topic[0], "type": "Topic", "properties": {"label": topic[1]}}],
    }
    (meta / f"{stem}.kg.json").write_text(json.dumps(kg), encoding="utf-8")
    return episode_slug(feed_id, episode_id, rel)


@pytest.fixture()
def built(tmp_path: Path) -> tuple[dict, dict]:
    root, data_dir = tmp_path / "corpus", tmp_path / "app"
    user = get_or_create_user(
        data_dir, provider="google", subject="golden", email="listener@example.com", name="L"
    )
    _write_ep(
        root, stem="0001", feed_id="fa", episode_id="e1", topic=("topic:ai-safety", "AI safety")
    )
    _write_ep(root, stem="0002", feed_id="fa", episode_id="e2", topic=("topic:memory", "Memory"))
    _write_ep(root, stem="0003", feed_id="fb", episode_id="e3", topic=("topic:sleep", "Sleep"))
    app_user_state.add_subscription(data_dir, user.user_id, {"feed_id": "fa"})  # follows fa only

    payload = ned.assemble_new_episodes_payload(root, data_dir, user.user_id, _NOW)
    assert payload is not None, "the followed show's unheard episodes produced no payload"
    email = ned.build_email_envelope(user, _COMMS, payload, _NOW)
    push = ned.build_push_envelope(
        user, _COMMS, {"endpoint": "https://push.example/sub/1", "keys": {}}, payload, _NOW
    )
    return email, push


def _errors(envelope: dict) -> list[str]:
    schema = json.loads(_SCHEMA.read_text(encoding="utf-8"))
    return [
        f"{list(e.path)}: {e.message}"
        for e in sorted(Draft202012Validator(schema).iter_errors(envelope), key=str)
    ]


def test_the_golden_is_what_the_builder_emits(built: tuple[dict, dict]) -> None:
    email, _ = built
    rendered = json.dumps(email, indent=2, sort_keys=True) + "\n"
    if os.environ.get("UPDATE_GOLDEN") == "1":
        _GOLDEN.write_text(rendered, encoding="utf-8")
    assert _GOLDEN.exists(), f"missing {_GOLDEN.name}; generate it with UPDATE_GOLDEN=1"
    assert _GOLDEN.read_text(encoding="utf-8") == rendered, (
        f"{_GOLDEN.name} no longer matches build_email_envelope's output. If the change is "
        "intended, regenerate with UPDATE_GOLDEN=1 and re-vendor it into homelab."
    )


def test_only_the_followed_show_is_announced(built: tuple[dict, dict]) -> None:
    email, _ = built
    slugs = email["payload"]["slugs"]
    assert len(slugs) == 2 and all("fb" not in s for s in slugs), slugs


def test_email_and_push_envelopes_validate(built: tuple[dict, dict]) -> None:
    email, push = built
    assert _errors(email) == []
    assert _errors(push) == []


def test_push_carries_the_subscription_where_the_worker_reads_it(built: tuple[dict, dict]) -> None:
    _, push = built
    assert push["recipient"]["push_subscription"]["endpoint"] == "https://push.example/sub/1"
    assert "subscription" not in push, "the top-level key no worker reads must not come back"
    assert push["consent_snapshot"]["unsubscribe_ref"]
